### PR TITLE
New form

### PR DESCRIPTION
**Pull request by johnsonquaid**
recipe.js is finished and works with the rest of the pages
Form doesn't update or have css

### CODE REVIEW

**Review by kserra1 — COMMENTED** [review]
I am getting many errors when running with this code. I am also not able to see any mock recipes. "Unhandled Promise Rejection: DataError: Failed to store record in an IDBObjectStore: Evaluating the object store's key path yielded a value that is not a valid key."

**Review by AtharvePandey — CHANGES_REQUESTED** [review]
your objects are showing up as undefined, but i am able to run the website. The form has no feedback if recipe submission was accepted or not. Also the form allows any input, i.e i can enter emojis for cooking time.

**Comment by AtharvePandey** [comment]
Still does not work on my end, tried incognito window and everything, made sure to run gitPull on my end. Getting following errors: 

recipelist.js:57 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at RecipeList.renderComments (recipelist.js:57:21)
    at RecipeList.renderRecipe (recipelist.js:48:24)
    at recipelist.js:29:46
    at Array.map (<anonymous>)
    at RecipeList.render (recipelist.js:29:27)
    at async HTMLButtonElement.displayRecipes (main.js:44:21)Understand this errorAI
2recipelist.js:57 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at RecipeList.renderComments (recipelist.js:57:21)
    at RecipeList.renderRecipe (recipelist.js:48:24)
    at recipelist.js:29:46
    at Array.map (<anonymous>)
    at RecipeList.render (recipelist.js:29:27)
    at async displayRecipes (main.js:44:21)

**Comment by AtharvePandey** [comment]
seeing this still:

image

**Review by AtharvePandey — APPROVED** [review]

**Comment by AtharvePandey** [comment]
Just ran this branch, and It works as it should. The image thing doesnt render for some reason but there are no errors, and we can figure out the image thing later:

image

the form also looks good and is detailed, it passes edge cases as well (only numbers in time input, etc.):

image

**Pull request merged**
